#ifndef MESSAGE_LEXICON_H
#define MESSAGE_LEXICON_H

#define NUM_MESSAGES 8

String messages[]  = {
  "MAN WE HATE SHITTY LETTERS",
  "HEY YOU! GET UP HERE AND IN MY MOUTH!",
  "BARE BUTTS = SAD BUTTS. USE PROTECTION",
  "EVER WANTED TO KNOW THE THRILL OF BEING EATEN?",
  "I CANT BREATHE. CAN SOMEONE MFNMGUFFL..",
  "KNOCK KNOCK",
  "BURNING MAN",
  "STOP SLIDING, MY THROAT IS BURNING, MAN!"
};

#endif
